// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViDf8C0lcZh5Hay2q1dxpYc7Qz-dC18U',
    appId: '1:44774909114:web:57bf60570a9cf78b96ce83',
    messagingSenderId: '44774909114',
    projectId: 'zeatszo-23d2d',
    authDomain: 'zeatszo-23d2d.firebaseapp.com',
    storageBucket: 'zeatszo-23d2d.firebasestorage.app',
    measurementId: 'G-H4Q5S663MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqTXGZBWw_odKrEoWo-9Yc2WC1_y2FutQ',
    appId: '1:44774909114:android:38cfc63437ce550b96ce83',
    messagingSenderId: '44774909114',
    projectId: 'zeatszo-23d2d',
    storageBucket: 'zeatszo-23d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjCOGkJIwrZAydYw4jhbtuCGf15TgvTn4',
    appId: '1:44774909114:ios:9b0ece9df9e076b096ce83',
    messagingSenderId: '44774909114',
    projectId: 'zeatszo-23d2d',
    storageBucket: 'zeatszo-23d2d.firebasestorage.app',
    iosBundleId: 'com.example.zeatzsoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjCOGkJIwrZAydYw4jhbtuCGf15TgvTn4',
    appId: '1:44774909114:ios:9b0ece9df9e076b096ce83',
    messagingSenderId: '44774909114',
    projectId: 'zeatszo-23d2d',
    storageBucket: 'zeatszo-23d2d.firebasestorage.app',
    iosBundleId: 'com.example.zeatzsoShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAViDf8C0lcZh5Hay2q1dxpYc7Qz-dC18U',
    appId: '1:44774909114:web:66014d03a223374096ce83',
    messagingSenderId: '44774909114',
    projectId: 'zeatszo-23d2d',
    authDomain: 'zeatszo-23d2d.firebaseapp.com',
    storageBucket: 'zeatszo-23d2d.firebasestorage.app',
    measurementId: 'G-Z57GJK6JD7',
  );
}
